version: '3.0'

services:

  mediawiki:
    image: docker-registry.wikimedia.org/dev/stretch-php72-fpm-apache2-xdebug:0.6.1-s1
    entrypoint: "/mwdd/entrypoint.sh"
    volumes:
     - ./wait-for-it.sh:/wait-for-it.sh:ro
     - ./mediawiki:/mwdd:ro
     - "${MEDIAWIKI_VOLUMES_CODE}:/var/www/html/w:cached"
     - "${MEDIAWIKI_VOLUMES_DATA:-mediawiki-data}:/var/www/html/w/data:delegated"
     - "${MEDIAWIKI_VOLUMES_IMAGES:-mediawiki-images}:/var/www/html/w/images/docker:delegated"
     - "${MEDIAWIKI_VOLUMES_LOGS:-mediawiki-logs}:/var/log/mediawiki:delegated"
    environment:
      # Used by various maintenance scripts to find MediaWiki.
      # Also required for /var/www/index.php - https://phabricator.wikimedia.org/T153882
      - MW_INSTALL_PATH=/var/www/html/w
      - VIRTUAL_HOST=*.mediawiki.mwdd.localhost
      - VIRTUAL_PORT=8080
      - XDEBUG_CONFIG=${MEDIAWIKI_XDEBUG_CONFIG:-}
    hostname: mediawiki.mwdd.localhost
    depends_on:
      - nginx-proxy
    dns:
      - 10.0.0.10
    dns_search:
      - mwdd.localhost
    networks:
      - dps

volumes:
  mediawiki-data:
  mediawiki-images:
  mediawiki-logs: