version: '3.0'

services:
  mysql:
    image: "${MYSQL_IMAGE:-mariadb:10.5}"
    environment:
      - MYSQL_ROOT_PASSWORD=toor
    hostname: mysql.mwdd.localhost
    dns:
      - 10.0.0.10
    networks:
      - dps
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql/main:/mwdd-custom
    entrypoint: "/mwdd-custom/entrypoint.sh"
    command: "mysqld"

volumes:
  mysql-data: