name: Go CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.13

    - name: Install golint
      run: go get -u golang.org/x/lint/golint

    - name: Install staticfiles
      run: go get bou.ke/staticfiles

    - name: Make
      run: make

    - name: Test
      run: make test

  integration-mwdd:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.13

    - name: Install staticfiles
      run: go get bou.ke/staticfiles

    - name: Make
      run: make

    - name: Setup hosts file
      run: sudo echo "127.0.0.1 default.mediawiki.mwdd.localhost" | sudo tee -a /etc/hosts

    - name: Fetch MediaWiki code to default location
      uses: actions/checkout@v2
      with:
        repository: wikimedia/mediawiki
        path: ~/dev/git/gerrit/mediawiki

    - name: mwdd create
      run: ./bin/mw mwdd create

    - name: mwdd env list
      run: ./bin/mw mwdd env list

    - continue-on-error: true
      run: sleep 10

    - continue-on-error: true
      run: docker ps -a

    - continue-on-error: true
      run: curl -s http://default.mediawiki.mwdd.localhost:8080
    - continue-on-error: true
      run: curl -s http://localhost:8080
    - continue-on-error: true
      run: curl -s http://127.0.0.1:8080
